export const ICONS = {
  menu: require('../assets/icons/menu.png'),
  marker: require('../assets/icons/marker.png'),
  navigate: require('../assets/icons/navigate.png'),
  heart: require('../assets/icons/heart.png'),
  check: require('../assets/icons/check.png'),
  dish: require('../assets/icons/dish.png'),
  food: require('../assets/icons/food.png'),
  share: require('../assets/icons/share.png'),
  filter: require('../assets/icons/filter.png'),
  bill: require('../assets/icons/bill.png'),
  profile: require('../assets/icons/profile.png'),
  Search: require('../assets/icons/Search.png'),
  sms: require('../assets/icons/sms.png'),
  star: require('../assets/icons/star.png'),
  cross: require('../assets/icons/cross.png'),
  demo: require('../assets/icons/demo.png'),
  dinein: require('../assets/icons/dinein.png'),
  bike: require('../assets/icons/bike.png'),
  bookmark: require('../assets/icons/bookmark.png'),
  backArrow: require('../assets/icons/backArrow.png'),
  coupon: require('../assets/icons/coupon.png'),
  coupontwo: require('../assets/icons/coupontwo.png'),
  rightArrow: require('../assets/icons/rightArrow.png'),
  uparrow: require('../assets/icons/uparrow.png'),
  clock: require('../assets/icons/clock.png'),
  table: require('../assets/icons/table.png'),
  minus: require('../assets/icons/minus.png'),
  add: require('../assets/icons/add.png'),
  call: require('../assets/icons/call.png'),
  mic: require('../assets/icons/mic.png'),
  shareIcon: require('../assets/icons/shareIcon.png'),
  Likeheart: require('../assets/icons/Likeheart.png'),
  circleRight: require('../assets/icons/circleRight.png'),
  circleCross: require('../assets/icons/circleCross.png'),
};

export const IMAGES = {
  DemoOne: require('../assets/images/DemoOne.png'),
  DemoTwo: require('../assets/images/DemoTwo.png'),
  DemoThree: require('../assets/images/DemoThree.png'),
  Demo4: require('../assets/images/Demo4.png'),
  Demo5: require('../assets/images/Demo5.png'),
  Demo6: require('../assets/images/Demo6.png'),
  Demo7: require('../assets/images/Demo7.png'),
  Demo8: require('../assets/images/Demo8.png'),
  Demo9: require('../assets/images/Demo9.png'),
  Demo10: require('../assets/images/Demo10.png'),
  Demo11: require('../assets/images/Demo11.png'),
  Demo12: require('../assets/images/Demo12.png'),
  Demo13: require('../assets/images/Demo13.png'),
  Demo14: require('../assets/images/Demo14.png'),
  Demo15: require('../assets/images/Demo15.png'),
  Demo16: require('../assets/images/Demo16.png'),
};

export const COLORS = {
  Primary: '#FA620F',
  Inactive: '#82807F',
  White: '#ffffff',
  Black: '#000000',
  TextBlack: '#181412',
  LightOrange: '#FDCEB5',
  LightOrangeOne: '#FFEFE7',
  LightOrangeTwo: '#FC965E',
  Background: '#F6F4F4',
  trnsparent: 'rgba(255, 239, 231, 0.25)',
};

export const FONTS = {
  Black: 'Roboto-Black',
  BlackItalic: 'Roboto-BlackItalic',
  Bold: 'Roboto-Bold',
  BoldItalic: 'Roboto-BoldItalic',
  ExtraBold: 'Roboto-ExtraBold',
  Italic: 'Roboto-Italic',
  Light: 'Roboto-Light',
  LightItalic: 'Roboto-LightItalic',
  Medium: 'Roboto-Medium',
  Regular: 'Roboto-Regular',
  Thin: 'Roboto-Thin',
  ThinItalic: 'Roboto-ThinItalic',
};
